[package]
name = "xbst"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
clap = { version = "4.5.31", features = ["derive"] }
zerocopy = { version = "0.8.26", features = ["derive"] }
